import type { Lang } from "@/i18n/lang"
import type { ProjectSlug } from "@/data/projects"

type CommercialId = "web-design" | "web-development" | "branding" | "graphic-design"
type CaseText = {
  sector: string
  discipline: string
  intro: string
  challenge: string
  idea: string
  application: string
  result: string
  deliverables: string[]
}

export type ProjectCase = CaseText & {
  services: CommercialId[]
  sections: { title: string; body: string }[]
}

export const PROJECT_CASE_LABELS = {
  ca: { sector: "Sector", scope: "Disciplines", challenge: "El repte", idea: "La idea", application: "El sistema en ús", result: "El resultat", deliverables: "Peces i àmbit del projecte", services: "Serveis relacionats" },
  es: { sector: "Sector", scope: "Disciplinas", challenge: "El reto", idea: "La idea", application: "El sistema en uso", result: "El resultado", deliverables: "Piezas y alcance del proyecto", services: "Servicios relacionados" },
  en: { sector: "Sector", scope: "Disciplines", challenge: "The challenge", idea: "The idea", application: "The system in use", result: "The outcome", deliverables: "Project scope and outputs", services: "Related services" },
} as const

// The narratives describe the work documented in the portfolio. Dates, business
// results, implementation stacks and client quotations are deliberately omitted
// because the source material does not establish them.
const CASES: Partial<Record<ProjectSlug, { services: CommercialId[]; copy: Record<Lang, CaseText> }>> = {
  vira: {
    services: ["web-design", "branding"],
    copy: {
      ca: {
        sector: "Producte digital · Adolescència i TDAH",
        discipline: "Disseny d’aplicació i identitat visual",
        intro: "VIRA és una aplicació concebuda per acompanyar adolescents amb TDAH en l’organització d’hàbits, tasques i registres emocionals. El projecte connecta el disseny de producte amb la identitat de marca: les pantalles, la il·lustració, el color i el to formen part d’una mateixa experiència. La proposta visual busca fer més entenedor què es pot fer en cada moment, amb seqüències curtes i una presència gràfica propera. El cas presenta aquest sistema de marca i d’interfície, des de les seves regles visuals fins a l’aplicació en mòbil.",
        challenge: "Una aplicació que reuneix rutines, tasques i emocions necessita ordenar continguts de naturalesa diferent. El repte de disseny era donar a cada funció un lloc clar sense convertir les pantalles en una acumulació d’instruccions. També calia mantenir un to adequat per a adolescents: amable i directe, amb personalitat pròpia. La jerarquia havia de permetre distingir la informació de context de l’acció següent, especialment en una pantalla petita.",
        idea: "La direcció del producte parteix de les microaccions. En lloc de presentar tota una rutina al mateix nivell, la interfície la divideix en passos identificables i dona resposta a cada acció. Aquesta lògica també guia la marca: color, il·lustració i llenguatge visual ajuden a crear continuïtat entre pantalles. La identitat no és una capa aplicada al final; participa en la manera com s’explica el producte i com s’orienta la navegació.",
        application: "El treball de UX/UI mòbil organitza tasques, hàbits i registres emocionals en seqüències curtes. Les regles de components mantenen consistents les accions i la jerarquia d’informació. La paleta i les il·lustracions aporten un caràcter recognoscible que es conserva en els diferents moments de l’experiència. Les imatges del projecte mostren la relació entre aquestes peces: elements d’identitat, recursos gràfics i pantalles comparteixen criteris, però cada element respon a una funció concreta dins del conjunt.",
        result: "El resultat presentat és un sistema connectat de marca i producte: identitat visual, paleta, il·lustració i disseny d’interfície mòbil. Permet entendre VIRA com una experiència coherent, amb un llenguatge que acompanya els continguts i les accions. El valor d’aquest cas és mostrar com una mateixa idea de disseny pot arribar des de la personalitat de marca fins a una pantalla concreta, mantenint clares les prioritats i les relacions entre els elements.",
        deliverables: ["UX/UI mòbil", "Identitat visual", "Paleta i il·lustració", "Llenguatge visual i regles de components"],
      },
      es: {
        sector: "Producto digital · Adolescencia y TDAH",
        discipline: "Diseño de aplicación e identidad visual",
        intro: "VIRA es una aplicación concebida para acompañar a adolescentes con TDAH en la organización de hábitos, tareas y registros emocionales. El proyecto conecta el diseño de producto con la identidad de marca: pantallas, ilustración, color y tono forman parte de una misma experiencia. La propuesta visual busca hacer más comprensible qué se puede hacer en cada momento, mediante secuencias cortas y una presencia gráfica cercana. Este caso presenta ese sistema de marca e interfaz, desde sus reglas visuales hasta su aplicación en móvil.",
        challenge: "Una aplicación que reúne rutinas, tareas y emociones necesita ordenar contenidos de distinta naturaleza. El reto de diseño consistía en dar un lugar claro a cada función sin convertir las pantallas en una acumulación de instrucciones. También era necesario mantener un tono adecuado para adolescentes: amable y directo, con personalidad propia. La jerarquía debía distinguir la información de contexto de la siguiente acción, especialmente en una pantalla pequeña.",
        idea: "La dirección del producto parte de las microacciones. En vez de presentar toda una rutina al mismo nivel, la interfaz la divide en pasos identificables y ofrece una respuesta a cada acción. Esta lógica también guía la marca: color, ilustración y lenguaje visual crean continuidad entre pantallas. La identidad participa en la forma de explicar el producto y orientar la navegación, conectando las decisiones gráficas con la estructura de la experiencia.",
        application: "El trabajo de UX/UI móvil organiza tareas, hábitos y registros emocionales en secuencias cortas. Las reglas de componentes mantienen consistentes las acciones y la jerarquía de información. La paleta y las ilustraciones aportan un carácter reconocible en distintos momentos de la experiencia. Las imágenes del proyecto muestran la relación entre estas piezas: elementos de identidad, recursos gráficos y pantallas comparten criterios, mientras cada elemento responde a una función concreta dentro del conjunto.",
        result: "El resultado presentado es un sistema conectado de marca y producto: identidad visual, paleta, ilustración y diseño de interfaz móvil. Permite entender VIRA como una experiencia coherente, con un lenguaje que acompaña contenidos y acciones. Este caso muestra cómo una misma idea de diseño puede trasladarse desde la personalidad de marca hasta una pantalla concreta, manteniendo claras las prioridades y las relaciones entre elementos. Las piezas documentan el alcance de diseño del proyecto.",
        deliverables: ["UX/UI móvil", "Identidad visual", "Paleta e ilustración", "Lenguaje visual y reglas de componentes"],
      },
      en: {
        sector: "Digital product · Adolescence and ADHD",
        discipline: "Application design and visual identity",
        intro: "VIRA is an application conceived to support teenagers with ADHD in organising habits, tasks and emotional check-ins. The project connects product design with brand identity: screens, illustration, colour and tone are parts of the same experience. Its visual approach aims to make the available actions easier to understand through short sequences and an approachable graphic language. This case presents the resulting brand and interface system, from its visual rules to their application on a mobile screen.",
        challenge: "An application bringing together routines, tasks and emotions has to organise very different kinds of content. The design challenge was to give each function a clear place without filling screens with instructions. The tone also needed to feel appropriate for teenagers: friendly and direct, with a recognisable personality. Information hierarchy had to separate context from the next available action, particularly within the limited space of a mobile interface.",
        idea: "The product direction starts with micro-actions. Rather than giving every part of a routine equal weight, the interface breaks it into identifiable steps and provides feedback on an action. This logic also informs the brand. Colour, illustration and visual language create continuity between screens. Identity takes part in explaining the product and guiding navigation, connecting graphic choices with the structure of the experience rather than acting as a separate decorative layer.",
        application: "The mobile UX/UI work organises tasks, habits and emotional check-ins into short sequences. Component rules keep actions and information hierarchy consistent. The palette and illustrations establish a recognisable character across different moments of the experience. The project images show how these pieces relate: identity elements, graphic assets and screens share criteria, while each element serves a particular purpose. That connection allows the overall personality to remain present in both expressive brand material and functional interface design.",
        result: "The documented output is a connected brand and product system: visual identity, palette, illustration and mobile interface design. Together they present VIRA as a coherent experience, with a visual language supporting its content and actions. The case demonstrates how a design idea can move from brand personality to an individual screen while keeping priorities and relationships clear. The portfolio materials describe the design scope and the artefacts produced for the project.",
        deliverables: ["Mobile UX/UI", "Visual identity", "Palette and illustration", "Visual language and component rules"],
      },
    },
  },
  galeon: {
    services: ["web-design", "graphic-design"],
    copy: {
      ca: {
        sector: "Cultura i patrimoni",
        discipline: "Disseny de producte i contingut interactiu",
        intro: "Galeón és una aplicació interactiva per recórrer la història de la monarquia espanyola a través de les Col·leccions Reials. La proposta connecta continguts, personatges i contextos, i inclou l’exploració d’edificis històrics i espais naturals gestionats per Patrimonio Nacional. El projecte de disseny tracta aquesta diversitat com una qüestió de navegació: com passar d’una visió general al detall d’una història mantenint el fil. El sistema visual i la jerarquia de contingut treballen junts per presentar el patrimoni en un entorn digital.",
        challenge: "Els objectes, els llocs, les persones i els períodes tenen relacions que una successió de pantalles aïllades no pot explicar per si sola. El repte era donar forma a aquestes connexions i mantenir una orientació clara durant el recorregut. La quantitat i la varietat de material requerien una estructura que pogués acollir continguts diferents sense perdre consistència. La interfície havia de deixar espai a la narració i alhora mostrar com continuar explorant.",
        idea: "La idea de disseny converteix el context històric en part de la navegació. Un lloc o un personatge serveix de punt d’entrada a una història i també de connexió amb altres continguts. Això permet construir un recorregut que alterna escala general i detall. La direcció visual acompanya aquesta lògica amb una jerarquia estable, perquè el material patrimonial mantingui protagonisme i la interfície doni continuïtat a la consulta.",
        application: "L’arquitectura d’informació relaciona llocs, persones, objectes i períodes. El disseny de producte defineix patrons d’interacció i maneres de presentar el contingut amb una base visual comuna. Les pantalles del projecte mostren com una estructura compartida pot donar cabuda a material divers sense exigir una lògica nova a cada pas. El sistema treballa tant l’ordre de lectura com la relació entre imatge, text i elements de navegació.",
        result: "El resultat és una proposta de producte interactiu amb arquitectura d’informació, jerarquia de contingut i un sistema visual reutilitzable. Les peces presentades documenten la traducció d’un conjunt patrimonial a una experiència digital amb criteris compartits. El cas il·lustra la relació entre disseny de continguts i UX/UI: donar forma a la informació també implica decidir quines relacions es fan visibles i com es manté el context durant l’exploració.",
        deliverables: ["Disseny de producte", "Arquitectura d’informació", "UX/UI i patrons d’interacció", "Sistema visual per a contingut patrimonial"],
      },
      es: {
        sector: "Cultura y patrimonio",
        discipline: "Diseño de producto y contenido interactivo",
        intro: "Galeón es una aplicación interactiva para recorrer la historia de la monarquía española a través de las Colecciones Reales. La propuesta conecta contenidos, personajes y contextos, e incluye la exploración de edificios históricos y espacios naturales gestionados por Patrimonio Nacional. El proyecto aborda esa diversidad como una cuestión de navegación: cómo pasar de una visión general al detalle de una historia manteniendo el hilo. El sistema visual y la jerarquía de contenido trabajan juntos para presentar el patrimonio en un entorno digital.",
        challenge: "Objetos, lugares, personas y periodos tienen relaciones que una sucesión de pantallas aisladas no puede explicar por sí sola. El reto era dar forma a esas conexiones y mantener una orientación clara durante el recorrido. La cantidad y variedad de material requerían una estructura capaz de acoger contenidos distintos con coherencia. La interfaz debía dejar espacio a la narración y, a la vez, mostrar las posibilidades de seguir explorando.",
        idea: "La idea de diseño convierte el contexto histórico en parte de la navegación. Un lugar o un personaje funciona como entrada a una historia y como conexión con otros contenidos. Así se construye un recorrido que alterna la escala general y el detalle. La dirección visual acompaña esa lógica mediante una jerarquía estable: el material patrimonial conserva el protagonismo y la interfaz da continuidad a la consulta.",
        application: "La arquitectura de información relaciona lugares, personas, objetos y periodos. El diseño de producto define patrones de interacción y formas de presentar el contenido sobre una base visual común. Las pantallas del proyecto muestran cómo una estructura compartida puede acoger materiales diferentes sin exigir una lógica nueva en cada paso. El sistema trabaja tanto el orden de lectura como la relación entre imagen, texto y elementos de navegación.",
        result: "El resultado es una propuesta de producto interactivo con arquitectura de información, jerarquía de contenido y un sistema visual reutilizable. Las piezas presentadas documentan la traducción de un conjunto patrimonial a una experiencia digital con criterios compartidos. El caso ilustra la relación entre diseño de contenidos y UX/UI: dar forma a la información implica decidir qué relaciones se hacen visibles y cómo se conserva el contexto durante la exploración.",
        deliverables: ["Diseño de producto", "Arquitectura de información", "UX/UI y patrones de interacción", "Sistema visual para contenido patrimonial"],
      },
      en: {
        sector: "Culture and heritage",
        discipline: "Product design and interactive content",
        intro: "Galeón is an interactive application for exploring the history of the Spanish monarchy through the Royal Collections. It connects content, people and historical contexts, including buildings and natural spaces managed by Patrimonio Nacional. The design project approaches this diversity as a navigation challenge: how to move from an overview into an individual story while keeping its context. The visual system and content hierarchy work together to present heritage material within a digital experience.",
        challenge: "Objects, places, people and periods are connected in ways that a sequence of isolated screens cannot explain on its own. The challenge was to make those connections visible while maintaining a clear sense of orientation. The range of material required a structure capable of accommodating different content consistently. The interface needed to give the narrative space while also showing how the exploration could continue and how each piece belonged within a wider context.",
        idea: "The design makes historical context part of the navigation. A place or a person can serve both as an entry into a story and as a link to other content. This creates a journey that moves between an overview and a closer examination. The visual direction supports that logic through a stable hierarchy, keeping the heritage material central while giving the interface a consistent role in guiding the experience.",
        application: "The information architecture relates places, people, objects and periods. Product design defines interaction patterns and ways of presenting content on a common visual foundation. The project screens show how a shared structure can accommodate varied material without requiring a different navigation logic at every step. The system addresses reading order as well as the relationship between images, text and navigation. Each is part of the same task of making historical content approachable through interaction.",
        result: "The output is an interactive product design combining information architecture, content hierarchy and a reusable visual system. The portfolio pieces document the translation of a heritage collection into a digital experience with shared design criteria. The case shows the relationship between content design and UX/UI: shaping information means deciding which connections become visible and how context is retained as the visitor moves through the material.",
        deliverables: ["Product design", "Information architecture", "UX/UI and interaction patterns", "Visual system for heritage content"],
      },
    },
  },
  arkuos: {
    services: ["branding", "graphic-design"],
    copy: {
      ca: {
        sector: "Educació i cultura",
        discipline: "Aplicació de marca i sistema de comunicació",
        intro: "Arkuos és un espai d’acció socioeducativa on infants, adolescents i joves poden crear, experimentar i aprendre. El centre articula activitats i projectes amb acompanyament i mentoria, en diferents districtes de treball equipats. La proposta combina els àmbits tangible, intangible i social, amb una atenció especial a la col·laboració. El treball de marca respon a aquesta diversitat: donar una expressió compartida a espais, activitats i materials sense reduir-los a una única peça gràfica.",
        challenge: "La identitat havia de funcionar per a edats, activitats i formats diferents. Un espai físic, una comunicació del programa i un material d’aprenentatge tenen necessitats d’informació pròpies, però han de permetre reconèixer el mateix projecte. El repte era construir una base comuna prou clara per ordenar aquest conjunt i prou flexible per conviure amb noves iniciatives. La varietat dels districtes formava part del context que el sistema havia d’explicar.",
        idea: "La resposta parteix d’un llenguatge visual modular. La marca es pot desplegar en aplicacions que identifiquen i relacionen els diferents àmbits del centre. La continuïtat es construeix amb regles compartides, mentre que cada peça disposa d’espai per expressar el seu contingut. Aquesta lògica encaixa amb un entorn de creació i aprenentatge: el sistema estableix un marc recognoscible i permet que hi convisquin activitats i maneres de participar diverses.",
        application: "El projecte treballa l’aplicació de marca, les peces de comunicació i el llenguatge visual del conjunt. La identitat es planteja per al contacte amb l’espai, el programa, els materials d’aprenentatge i els suports digitals. La jerarquia d’informació té una funció pràctica: distingir àmbits i continguts sense separar-los de la identitat comuna. Les imatges mostren diferents expressions del sistema i la relació entre marca i aplicació.",
        result: "El resultat presentat és un sistema modular d’aplicació de marca per a un entorn socioeducatiu. Dona criteris compartits a la comunicació i permet representar els districtes com a parts d’un mateix projecte. El cas mostra com el disseny gràfic pot ordenar una iniciativa amb molts punts de contacte: la identitat es reconeix en la continuïtat de les peces, en la manera de presentar informació i en la relació entre les seves aplicacions.",
        deliverables: ["Aplicacions d’identitat", "Sistema visual modular", "Peces de comunicació", "Jerarquia d’informació"],
      },
      es: {
        sector: "Educación y cultura",
        discipline: "Aplicación de marca y sistema de comunicación",
        intro: "Arkuos es un espacio de acción socioeducativa donde niños, adolescentes y jóvenes pueden crear, experimentar y aprender. El centro articula actividades y proyectos con acompañamiento y mentoría en distintos distritos de trabajo equipados. La propuesta conecta los ámbitos tangible, intangible y social, prestando especial atención a la colaboración. El trabajo de marca responde a esa diversidad: dar una expresión compartida a espacios, actividades y materiales sin reducirlos a una única pieza gráfica.",
        challenge: "La identidad debía funcionar para edades, actividades y formatos diferentes. Un espacio físico, una comunicación del programa y un material de aprendizaje tienen necesidades de información propias, pero deben permitir reconocer el mismo proyecto. El reto era construir una base común suficientemente clara para ordenar el conjunto y flexible para convivir con nuevas iniciativas. La variedad de los distritos formaba parte del contexto que el sistema debía explicar.",
        idea: "La respuesta parte de un lenguaje visual modular. La marca se despliega en aplicaciones que identifican y relacionan los distintos ámbitos del centro. La continuidad se construye con reglas compartidas, mientras cada pieza dispone de espacio para expresar su contenido. Esta lógica encaja con un entorno de creación y aprendizaje: el sistema establece un marco reconocible y permite que convivan actividades y formas de participar diversas dentro de una misma identidad.",
        application: "El proyecto trabaja la aplicación de marca, las piezas de comunicación y el lenguaje visual del conjunto. La identidad se plantea para el contacto con el espacio, el programa, los materiales de aprendizaje y los soportes digitales. La jerarquía de información cumple una función práctica: distinguir ámbitos y contenidos manteniendo su vínculo con la identidad común. Las imágenes muestran diferentes expresiones del sistema y la relación entre marca y aplicación.",
        result: "El resultado presentado es un sistema modular de aplicación de marca para un entorno socioeducativo. Aporta criterios compartidos a la comunicación y permite representar los distritos como partes del mismo proyecto. El caso muestra cómo el diseño gráfico puede ordenar una iniciativa con muchos puntos de contacto: la identidad se reconoce en la continuidad de las piezas, en la forma de presentar información y en la relación entre sus aplicaciones.",
        deliverables: ["Aplicaciones de identidad", "Sistema visual modular", "Piezas de comunicación", "Jerarquía de información"],
      },
      en: {
        sector: "Education and culture",
        discipline: "Brand application and communication system",
        intro: "Arkuos is a socio-educational space where children, teenagers and young people can create, experiment and learn. The centre brings together activities and projects with guidance and mentorship across different equipped working districts. Its approach connects tangible, intangible and social experiences, with a focus on collaboration. The brand work responds to that variety by giving spaces, activities and materials a shared expression that can extend beyond any single graphic piece.",
        challenge: "The identity needed to work across different ages, activities and formats. A physical space, a programme announcement and a learning material each have their own information requirements, yet all need to be recognisable as parts of the same project. The challenge was to establish a common foundation that could organise the whole and accommodate new initiatives. The variety of working districts was part of the context the system needed to communicate.",
        idea: "The response starts with a modular visual language. The brand can be applied in ways that identify and connect different parts of the centre. Shared rules create continuity while leaving each piece room to communicate its own content. This approach fits an environment for creation and learning: the system establishes a recognisable framework in which different activities and forms of participation can coexist without losing their connection to the overall identity.",
        application: "The project addresses brand application, communication pieces and a shared visual language. The identity considers the physical space, programme communication, learning materials and digital touchpoints. Information hierarchy serves a practical purpose: distinguishing activities and content while maintaining their relationship to the wider project. The portfolio images show different expressions of the system and how the brand connects with its applications. Those relationships make the identity a working framework for communication.",
        result: "The documented result is a modular brand application system for a socio-educational environment. It gives communication shared criteria and represents the districts as parts of one project. The case illustrates how graphic design can organise an initiative with varied touchpoints: recognition comes from continuity across pieces, the presentation of information and the relationships between applications. The portfolio brings these expressions together to show the scope and consistency of the visual system.",
        deliverables: ["Identity applications", "Modular visual system", "Communication pieces", "Information hierarchy"],
      },
    },
  },
  "el-xiringuito": {
    services: ["branding", "graphic-design"],
    copy: {
      ca: {
        sector: "Restauració",
        discipline: "Identitat visual, cartes i retolació",
        intro: "El Xiringuito és una identitat visual per a un restaurant de costa. La direcció gràfica parteix d’una estètica mediterrània, lleugera i lluminosa, i la trasllada a peces que formen part de l’experiència quotidiana del restaurant. Color, tipografia i composició en capes construeixen un univers compartit per a menús, cartes, posavasos, retolació i comunicació digital. El projecte connecta el caràcter del lloc amb els suports on la marca es troba amb les persones.",
        challenge: "Una identitat de restauració ha de comunicar ambient i també informació pràctica. La carta necessita ordre de lectura; la retolació, reconeixement; i una peça digital ha de conservar personalitat en un altre format. El repte era donar coherència a aquestes situacions sense fer que totes les aplicacions fossin idèntiques. La sensació mediterrània havia de viure en les decisions de disseny i mantenir-se quan canviava el suport o el contingut.",
        idea: "El concepte gràfic recull la sensació d’estiu: sal, sorra, ombra i ritme. La composició en capes, la tipografia i el color donen forma a aquesta direcció. El sistema combina expressivitat amb espais de lectura clara, de manera que la identitat pot acompanyar tant una peça visual com una carta amb informació. La marca es construeix en la relació entre aquests recursos i en la manera d’adaptar-los a cada aplicació.",
        application: "Les peces presentades inclouen menús i cartes, posavasos, retolació i recursos per a comunicació digital. Cada format demana una escala i una jerarquia diferents. El treball de composició connecta plats, preus o missatges amb un llenguatge visual recognoscible. La galeria mostra aquesta extensió de la marca: elements pensats per conviure amb l’experiència física del restaurant i peces que traslladen el mateix caràcter als canals de comunicació.",
        result: "El resultat és una identitat aplicada que reuneix suports impresos, senyalística i peces digitals dins d’un mateix univers mediterrani. El cas posa en relació marca i ús: com una direcció visual pot expressar el caràcter d’un restaurant i ordenar la seva informació. Les aplicacions documentades mostren l’abast del treball de branding i disseny gràfic, així com la continuïtat entre els diferents moments de contacte amb la marca.",
        deliverables: ["Identitat visual", "Sistema de menús i cartes", "Posavasos i retolació", "Peces de comunicació digital"],
      },
      es: {
        sector: "Restauración",
        discipline: "Identidad visual, cartas y rotulación",
        intro: "El Xiringuito es una identidad visual para un restaurante de costa. La dirección gráfica parte de una estética mediterránea, ligera y luminosa, y la traslada a piezas que forman parte de la experiencia cotidiana del restaurante. Color, tipografía y composición en capas construyen un universo compartido para menús, cartas, posavasos, rotulación y comunicación digital. El proyecto conecta el carácter del lugar con los soportes en los que la marca se encuentra con las personas.",
        challenge: "Una identidad de restauración debe comunicar ambiente e información práctica. La carta necesita orden de lectura; la rotulación, reconocimiento; y una pieza digital debe conservar personalidad en otro formato. El reto era dar coherencia a estas situaciones sin hacer que todas las aplicaciones fueran idénticas. La sensación mediterránea debía estar presente en las decisiones de diseño y mantenerse cuando cambiara el soporte o el contenido de cada pieza.",
        idea: "El concepto gráfico recoge la sensación del verano: sal, arena, sombra y ritmo. La composición en capas, la tipografía y el color dan forma a esa dirección. El sistema combina expresividad con espacios de lectura clara, de modo que la identidad puede acompañar tanto una pieza visual como una carta con información. La marca se construye en la relación entre estos recursos y en su adaptación a cada aplicación.",
        application: "Las piezas presentadas incluyen menús y cartas, posavasos, rotulación y recursos para comunicación digital. Cada formato exige una escala y una jerarquía distintas. El trabajo de composición conecta platos, precios o mensajes con un lenguaje visual reconocible. La galería muestra esa extensión de la marca: elementos pensados para convivir con la experiencia física del restaurante y piezas que trasladan el mismo carácter a los canales de comunicación.",
        result: "El resultado es una identidad aplicada que reúne soportes impresos, señalética y piezas digitales dentro del mismo universo mediterráneo. El caso relaciona marca y uso: cómo una dirección visual puede expresar el carácter de un restaurante y ordenar su información. Las aplicaciones documentadas muestran el alcance del trabajo de branding y diseño gráfico, así como la continuidad entre los distintos momentos de contacto con la marca.",
        deliverables: ["Identidad visual", "Sistema de menús y cartas", "Posavasos y rotulación", "Piezas de comunicación digital"],
      },
      en: {
        sector: "Restaurants",
        discipline: "Visual identity, menus and signage",
        intro: "El Xiringuito is a visual identity for a coastal restaurant. Its graphic direction takes a light, bright Mediterranean aesthetic into pieces that belong to the restaurant’s everyday experience. Colour, typography and layered composition build a shared visual world for menus, cards, coasters, signage and digital communication. The project connects the character of the place with the materials through which people encounter the brand, extending the identity across practical and expressive applications.",
        challenge: "A restaurant identity needs to communicate atmosphere as well as useful information. A menu requires a clear reading order; signage needs recognition; a digital piece has to retain personality in a different format. The challenge was to bring these situations together without making every application identical. The Mediterranean character needed to be present in the design decisions and remain recognisable as the medium and content changed from one piece to another.",
        idea: "The graphic concept draws on the feeling of summer: salt, sand, shade and rhythm. Layered composition, typography and colour give that direction a visual form. The system balances expressive layouts with clear reading areas, allowing the identity to support both an image-led piece and an information-rich menu. The brand takes shape through the relationship between these resources and how they adapt to each application within the broader visual language.",
        application: "The documented pieces include menus, cards, coasters, signage and assets for digital communication. Each format calls for a different scale and hierarchy. Composition brings dishes, prices or messages into a recognisable visual language. The gallery shows that extension of the brand: elements designed to sit within the restaurant’s physical experience and communication pieces that carry the same character into other channels. The shared system keeps those uses connected while making room for their particular requirements.",
        result: "The outcome is an applied identity bringing print materials, signage and digital pieces into the same Mediterranean visual world. The case connects brand design with use: how a visual direction can express a restaurant’s character and organise its information. The documented applications show the scope of the branding and graphic design work and the continuity between different encounters with the brand, from a menu to a communication asset.",
        deliverables: ["Visual identity", "Menu system", "Coasters and signage", "Digital communication assets"],
      },
    },
  },
  enteza: {
    services: ["branding", "graphic-design"],
    copy: {
      ca: {
        sector: "Mobiliari i esdeveniments",
        discipline: "Identitat i presentació de producte",
        intro: "Enteza és una marca de lloguer de mobiliari i parament per a esdeveniments, amb una proposta centrada en disseny, elegància i qualitat. El projecte treballa la relació entre identitat visual, catàleg i presentació de producte. La col·lecció té categories i sèries que han de poder-se consultar amb claredat, mantenint el caràcter de la marca. El sistema planteja una manera compartida d’ordenar les peces i de presentar-les en materials de producte i comunicació digital.",
        challenge: "Una col·lecció àmplia necessita explicar què ofereix i com s’organitzen les opcions. El repte era mantenir una presentació coherent sense diluir les diferències entre productes i famílies. En un catàleg, la imatge i la informació han de permetre passar de la visió general al detall. La identitat havia d’acompanyar aquest recorregut i conservar una presència reconeixible, tant en una pàgina de producte com en una peça de comunicació.",
        idea: "La direcció combina un sistema de marca amb una estructura de catàleg. El caràcter visual de l’oferta es manté a través de criteris compartits de composició, tractament d’imatge i jerarquia. Les categories i les sèries permeten ordenar la col·lecció, mentre que la presentació de cada peça conserva la seva especificitat. La identitat dona continuïtat al conjunt i ajuda a llegir els materials com a parts d’una mateixa proposta.",
        application: "El treball s’aplica al catàleg, a la comunicació digital i als materials de presentació de producte. Cada peça ocupa un lloc dins d’una estructura comuna, amb un tractament visual i una jerarquia d’informació consistents. Aquesta relació entre sistema i contingut és el centre del cas: el disseny estableix una base per presentar una col·lecció diversa i manté connectades les seves expressions. La galeria documenta la marca a través d’aquestes aplicacions.",
        result: "El resultat presentat és un sistema d’identitat i de presentació de producte que reuneix catàleg i comunicació. La seva estructura pot acollir noves peces sense haver de replantejar el llenguatge visual de cada pàgina. El projecte mostra com el branding es concreta en decisions d’ordenació i composició: la marca es reconeix en la imatge general i també en la manera de presentar informació, relacionar categories i donar continuïtat als materials.",
        deliverables: ["Sistema d’identitat", "Estructura de catàleg", "Disseny de peces digitals", "Presentació de producte"],
      },
      es: {
        sector: "Mobiliario y eventos",
        discipline: "Identidad y presentación de producto",
        intro: "Enteza es una marca de alquiler de mobiliario y menaje para eventos, con una propuesta centrada en diseño, elegancia y calidad. El proyecto trabaja la relación entre identidad visual, catálogo y presentación de producto. La colección tiene categorías y series que deben poder consultarse con claridad, manteniendo el carácter de la marca. El sistema plantea una forma compartida de ordenar las piezas y presentarlas en materiales de producto y comunicación digital.",
        challenge: "Una colección amplia necesita explicar qué ofrece y cómo se organizan las opciones. El reto era mantener una presentación coherente sin diluir las diferencias entre productos y familias. En un catálogo, imagen e información deben permitir pasar de la visión general al detalle. La identidad debía acompañar ese recorrido y conservar una presencia reconocible, tanto en una página de producto como en una pieza de comunicación.",
        idea: "La dirección combina un sistema de marca con una estructura de catálogo. El carácter visual de la oferta se mantiene mediante criterios compartidos de composición, tratamiento de imagen y jerarquía. Las categorías y series permiten ordenar la colección, mientras la presentación de cada pieza conserva su especificidad. La identidad da continuidad al conjunto y ayuda a leer los materiales como partes de una misma propuesta, conectando la oferta con su expresión gráfica.",
        application: "El trabajo se aplica al catálogo, la comunicación digital y los materiales de presentación de producto. Cada pieza ocupa un lugar dentro de una estructura común, con un tratamiento visual y una jerarquía de información consistentes. Esa relación entre sistema y contenido es el centro del caso: el diseño establece una base para presentar una colección diversa y mantiene conectadas sus expresiones. La galería documenta la marca a través de esas aplicaciones.",
        result: "El resultado presentado es un sistema de identidad y presentación de producto que reúne catálogo y comunicación. Su estructura puede acoger nuevas piezas sin replantear el lenguaje visual de cada página. El proyecto muestra cómo el branding se concreta en decisiones de organización y composición: la marca se reconoce en la imagen general y en la forma de presentar información, relacionar categorías y dar continuidad a sus materiales.",
        deliverables: ["Sistema de identidad", "Estructura de catálogo", "Diseño de piezas digitales", "Presentación de producto"],
      },
      en: {
        sector: "Furniture and events",
        discipline: "Identity and product presentation",
        intro: "Enteza is a furniture and tableware rental brand for events, with an emphasis on design, elegance and quality. The project connects visual identity, catalogue structure and product presentation. Its collection contains categories and series that need to be clear to browse while preserving the character of the brand. The system establishes a shared way to organise the pieces and present them across product materials and digital communication, bringing the offer and its graphic expression together.",
        challenge: "A broad collection needs to communicate what it contains and how its options are organised. The challenge was to maintain a consistent presentation without losing the differences between products and families. In a catalogue, imagery and information need to support the transition from an overview to an individual piece. The identity had to accompany that journey and remain recognisable in both a product page and a communication asset.",
        idea: "The design direction combines a brand system with a catalogue structure. Shared criteria for composition, image treatment and hierarchy keep the offer visually coherent. Categories and series organise the collection while the presentation of each piece retains its individual character. The identity creates continuity and helps the materials read as parts of the same offer. That connection makes product presentation a central expression of the brand rather than a separate graphic exercise.",
        application: "The work applies to the catalogue, digital communication and product presentation materials. Each piece has a place within a common structure, with consistent image treatment and information hierarchy. The relationship between system and content is central to the case: design establishes a foundation for presenting a varied collection while keeping its expressions connected. The gallery documents the identity through these applications and shows how product material belongs within the wider visual language.",
        result: "The documented output is an identity and product presentation system connecting catalogue and communication. Its structure can accommodate additional pieces without requiring a new visual language for every page. The project shows how branding becomes concrete through organisation and composition: the brand appears in the overall image and in the way information is presented, categories are related and materials remain consistent. These applications establish the design scope shown in the portfolio.",
        deliverables: ["Identity system", "Catalogue structure", "Digital asset design", "Product presentation"],
      },
    },
  },
  "gent-gran-de-calonge-i-sant-antoni": {
    services: ["branding", "graphic-design"],
    copy: {
      ca: {
        sector: "Sector públic · Comunitat",
        discipline: "Identitat i comunicació institucional",
        intro: "Gent Gran de Calonge i Sant Antoni és un projecte d’identitat per a les activitats adreçades a les persones grans del municipi. Desenvolupat per a la regidoria de serveis socials, el treball busca donar cohesió a la comunicació del programa. Un to proper i positiu, un sistema gràfic simple i una jerarquia clara connecten cartelleria, xarxes i materials informatius. La identitat es planteja per conviure amb els formats i les necessitats de la comunicació municipal.",
        challenge: "Una activitat pot arribar al públic a través d’un cartell, una publicació digital o un material informatiu. El repte consistia a mantenir una identitat comuna i una lectura clara en aquestes situacions. La informació havia de conservar prioritat, amb una expressió propera que ajudés a reconèixer el programa. El sistema també havia de poder-se reproduir amb coherència en un context institucional, on les peces canvien de contingut i format.",
        idea: "La direcció visual combina simplicitat, contrast i repetició. Un llenguatge gràfic memorable permet identificar el conjunt d’activitats i donar-los una presència compartida. El to positiu acompanya la comunicació sense desplaçar la informació. El treball de jerarquia ordena els continguts per fer explícita la relació entre el programa i cada peça, mentre que les regles visuals mantenen la continuïtat entre suports físics i digitals.",
        application: "La identitat es concreta en cartelleria, contingut per a xarxes i materials informatius. La llegibilitat i el contrast orienten la composició, amb una atenció especial a les condicions en què es pot consultar cada suport. Les aplicacions comparteixen recursos i criteris d’ordre de lectura. La galeria presenta aquesta família de peces com un sistema de comunicació: expressions diferents d’un mateix programa municipal, unides per llenguatge gràfic i to.",
        result: "El resultat és un conjunt pràctic d’aplicacions d’identitat per a comunicació pública. La marca dona una presència consistent a les activitats i connecta peces impreses i digitals. El cas mostra el paper del disseny gràfic en una iniciativa comunitària: fer recognoscible un programa, ordenar la informació i donar criteris compartits a la seva comunicació. Les peces publicades documenten el sistema visual i les formes en què s’aplica.",
        deliverables: ["Identitat visual", "Sistema de comunicació", "Cartelleria i materials informatius", "Peces per a xarxes"],
      },
      es: {
        sector: "Sector público · Comunidad",
        discipline: "Identidad y comunicación institucional",
        intro: "Gent Gran de Calonge i Sant Antoni es un proyecto de identidad para las actividades dirigidas a las personas mayores del municipio. Desarrollado para la concejalía de servicios sociales, el trabajo busca dar cohesión a la comunicación del programa. Un tono cercano y positivo, un sistema gráfico simple y una jerarquía clara conectan cartelería, redes y materiales informativos. La identidad está planteada para convivir con los formatos y necesidades de la comunicación municipal.",
        challenge: "Una actividad puede llegar al público a través de un cartel, una publicación digital o un material informativo. El reto consistía en mantener una identidad común y una lectura clara en esas situaciones. La información debía conservar prioridad, con una expresión cercana que ayudara a reconocer el programa. El sistema también debía poder reproducirse con coherencia en un contexto institucional, donde las piezas cambian de contenido y formato.",
        idea: "La dirección visual combina simplicidad, contraste y repetición. Un lenguaje gráfico memorable permite identificar el conjunto de actividades y darles una presencia compartida. El tono positivo acompaña la comunicación manteniendo la información en primer plano. El trabajo de jerarquía ordena los contenidos para hacer explícita la relación entre el programa y cada pieza, mientras las reglas visuales mantienen la continuidad entre soportes físicos y digitales.",
        application: "La identidad se concreta en cartelería, contenido para redes y materiales informativos. Legibilidad y contraste orientan la composición, con atención a las condiciones en que puede consultarse cada soporte. Las aplicaciones comparten recursos y criterios de orden de lectura. La galería presenta esta familia de piezas como un sistema de comunicación: expresiones diferentes de un mismo programa municipal, unidas por lenguaje gráfico y tono.",
        result: "El resultado es un conjunto práctico de aplicaciones de identidad para comunicación pública. La marca aporta una presencia consistente a las actividades y conecta piezas impresas y digitales. El caso muestra el papel del diseño gráfico en una iniciativa comunitaria: hacer reconocible un programa, ordenar la información y dar criterios compartidos a su comunicación. Las piezas publicadas documentan el sistema visual y las formas en que se aplica.",
        deliverables: ["Identidad visual", "Sistema de comunicación", "Cartelería y materiales informativos", "Piezas para redes"],
      },
      en: {
        sector: "Public sector · Community",
        discipline: "Identity and institutional communication",
        intro: "Gent Gran de Calonge i Sant Antoni is an identity project for activities aimed at older adults in the municipality. Developed for the municipal social services department, the work brings coherence to the programme’s communication. A friendly, positive tone, a simple graphic system and a clear hierarchy connect posters, social content and information materials. The identity is designed to work within the formats and practical requirements of municipal communication.",
        challenge: "An activity may reach its audience through a poster, a digital post or an information sheet. The challenge was to maintain a common identity and clear reading across those situations. Information needed to remain prominent, with an approachable expression that made the programme recognisable. The system also had to be reproducible in an institutional setting, where pieces change in content and format while continuing to represent the same programme.",
        idea: "The visual direction combines simplicity, contrast and repetition. A memorable graphic language identifies the collection of activities and gives them a shared public presence. The positive tone supports communication while keeping information central. Hierarchy makes the relationship between the programme and each piece explicit, while visual rules maintain continuity across physical and digital materials. Together these decisions give varied messages a recognisable home within the identity.",
        application: "The identity takes shape in posters, social content and information materials. Legibility and contrast guide composition, with attention to the conditions in which each medium may be read. Applications share graphic resources and reading-order principles. The gallery presents this family of pieces as a communication system: different expressions of a municipal programme, connected by visual language and tone. Each format retains its own role within that common framework.",
        result: "The outcome is a practical set of identity applications for public communication. The brand gives activities a consistent presence and connects printed and digital pieces. The case demonstrates the role of graphic design in a community initiative: making a programme recognisable, organising information and giving its communication shared criteria. The published portfolio pieces document the visual system and how it translates into the different materials shown in the project.",
        deliverables: ["Visual identity", "Communication system", "Posters and information materials", "Social media assets"],
      },
    },
  },
  logoteca: {
    services: ["branding", "graphic-design"],
    copy: {
      ca: {
        sector: "Disseny de marca · Col·lecció",
        discipline: "Logotips i síntesi visual",
        intro: "Logoteca reuneix una selecció de dissenys de logotip de PALSEC. És una col·lecció centrada en la síntesi visual: com una idea pren forma a través de lletres, símbols, proporcions i contrast. Les peces permeten observar respostes diferents dins d’una mateixa pràctica de disseny. La galeria presenta les marques de manera individual i també en conjunt, perquè se’n puguin llegir tant els detalls de construcció com les diferències de caràcter entre propostes.",
        challenge: "Un logotip concentra una part important de la identitat en molt pocs elements. Aquesta economia formal obliga a precisar la relació entre traç, espai, ritme i proporció. El repte que travessa la col·lecció és trobar expressions diferenciades sense dependre d’una acumulació de recursos. Cada peça planteja la seva manera de ser reconeixible, ja sigui a partir d’una forma tipogràfica, d’una construcció geomètrica o de la relació entre signe i paraula.",
        idea: "La col·lecció explora diferents formes de síntesi. En algunes peces el pes recau en les lletres; en d’altres, en el símbol o en el contrast entre elements. Aquesta diversitat permet llegir el disseny de logotips com una recerca de proporció i significat. La selecció no imposa una mateixa solució a totes les marques: presenta diferents llenguatges que comparteixen una atenció a la forma i a les seves relacions internes.",
        application: "La presentació en quadrícula facilita una primera lectura del conjunt. Cada peça es pot ampliar per observar-ne la composició, els espais i el detall tipogràfic. Aquesta manera de mostrar l’arxiu dona protagonisme als signes i permet comparar aproximacions sense barrejar-les amb altres aplicacions. El focus del cas és el disseny dels logotips i el seu llenguatge visual, com a elements que poden formar part d’un sistema d’identitat més ampli.",
        result: "El resultat és un arxiu visual de logotips que documenta una pràctica de marca a través de peces concretes. La col·lecció mostra com recursos limitats poden produir caràcters diferents i com la precisió formal participa en el reconeixement d’una identitat. Logoteca complementa els projectes aplicats del portafolis: permet mirar de prop una escala específica del branding, la del signe, abans de la seva extensió a altres suports.",
        deliverables: ["Disseny de logotips", "Composició tipogràfica", "Construcció de símbols", "Síntesi visual de marca"],
      },
      es: {
        sector: "Diseño de marca · Colección",
        discipline: "Logotipos y síntesis visual",
        intro: "Logoteca reúne una selección de diseños de logotipo de PALSEC. Es una colección centrada en la síntesis visual: cómo una idea toma forma a través de letras, símbolos, proporciones y contraste. Las piezas permiten observar respuestas diferentes dentro de una misma práctica de diseño. La galería presenta las marcas de forma individual y en conjunto, para poder leer tanto los detalles de construcción como las diferencias de carácter entre propuestas.",
        challenge: "Un logotipo concentra una parte importante de la identidad en muy pocos elementos. Esa economía formal obliga a precisar la relación entre trazo, espacio, ritmo y proporción. El reto que recorre la colección es encontrar expresiones diferenciadas sin depender de una acumulación de recursos. Cada pieza plantea su forma de ser reconocible, desde una construcción tipográfica o geométrica hasta la relación entre un signo y una palabra.",
        idea: "La colección explora distintas formas de síntesis. En algunas piezas el peso recae en las letras; en otras, en el símbolo o en el contraste entre elementos. Esta diversidad permite leer el diseño de logotipos como una búsqueda de proporción y significado. La selección presenta lenguajes diferentes que comparten atención a la forma y a sus relaciones internas, con una respuesta propia para cada una de las marcas mostradas.",
        application: "La presentación en cuadrícula facilita una primera lectura del conjunto. Cada pieza se puede ampliar para observar su composición, espacios y detalle tipográfico. Esta forma de mostrar el archivo da protagonismo a los signos y permite comparar aproximaciones sin mezclarlas con otras aplicaciones. El foco del caso es el diseño de los logotipos y su lenguaje visual, como elementos que pueden formar parte de un sistema de identidad más amplio.",
        result: "El resultado es un archivo visual de logotipos que documenta una práctica de marca mediante piezas concretas. La colección muestra cómo recursos limitados pueden producir caracteres diferentes y cómo la precisión formal participa en el reconocimiento de una identidad. Logoteca complementa los proyectos aplicados del portafolio: permite mirar de cerca una escala específica del branding, la del signo, antes de su extensión a otros soportes y aplicaciones.",
        deliverables: ["Diseño de logotipos", "Composición tipográfica", "Construcción de símbolos", "Síntesis visual de marca"],
      },
      en: {
        sector: "Brand design · Collection",
        discipline: "Logo design and visual synthesis",
        intro: "Logoteca brings together a selection of logo designs by PALSEC. The collection focuses on visual synthesis: how an idea takes shape through letterforms, symbols, proportions and contrast. Its pieces show different responses within a shared design practice. The gallery presents the marks individually and as a group, allowing their construction details and differences in character to be considered at both scales, from the overall selection to an individual composition.",
        challenge: "A logo concentrates a significant part of an identity into very few elements. That economy requires precision in the relationships between strokes, space, rhythm and proportion. The challenge running through the collection is to find distinctive expressions without relying on an accumulation of graphic resources. Each piece approaches recognition in its own way, through a letterform, geometric construction or the relationship between a symbol and a word.",
        idea: "The collection explores different kinds of visual synthesis. Some pieces place the emphasis on letters; others on a symbol or on contrast between elements. This variety presents logo design as an exploration of proportion and meaning. The selection brings together different visual languages with a shared attention to form and internal relationships. Each mark can be considered as its own response while also contributing to the broader study shown in the archive.",
        application: "The grid provides an initial view of the collection. Individual pieces can be enlarged to examine composition, spacing and typographic details. This presentation gives the marks prominence and makes it possible to compare approaches without combining them with other applications. The focus of the case is the design of the logos and their visual language, as elements capable of belonging to a broader identity system. The gallery supports both a quick overview and a closer reading.",
        result: "The outcome is a visual archive of logos documenting brand design through specific pieces. The collection shows how a limited set of resources can produce different characters and how formal precision contributes to recognition. Logoteca complements the applied projects in the portfolio: it allows a closer look at one scale of branding, the individual mark, before its extension into other media. Together the pieces offer a view of the studio’s work in visual synthesis.",
        deliverables: ["Logo design", "Typographic composition", "Symbol construction", "Brand visual synthesis"],
      },
    },
  },
}

export function getProjectCase(slug: ProjectSlug, lang: Lang): ProjectCase | null {
  const entry = CASES[slug]
  if (!entry) return null
  const copy = entry.copy[lang]
  const labels = PROJECT_CASE_LABELS[lang]
  return {
    ...copy,
    services: entry.services,
    sections: [
      { title: labels.challenge, body: copy.challenge },
      { title: labels.idea, body: copy.idea },
      { title: labels.application, body: copy.application },
      { title: labels.result, body: copy.result },
    ],
  }
}
