import type { Lang } from '@/i18n/lang'

export const SITE_COPY = {
  es: {
    headline: 'Diseñamos marcas y experiencias digitales que la gente recuerda',
    intro: 'PALSEC es un estudio de diseño y desarrollo de la Costa Brava que trabaja con empresas y organizaciones de Girona y de otros lugares. Conectamos estrategia, identidad y tecnología para dar forma a marcas, webs y productos digitales con criterio.',
    services: 'De la marca a la experiencia digital',
    serviceIntro: 'Una identidad y una web responden a preguntas distintas, pero deben hablar el mismo idioma. Podemos trabajar una parte concreta o acompañar el recorrido completo: definir qué necesitas comunicar, diseñar cómo expresarlo y construir los soportes que lo hacen posible.',
    projects: 'Ideas que toman forma',
    proof: 'El portfolio reúne identidades, sistemas gráficos e interfaces. El Xiringuito muestra una identidad aplicada a restauración; Gent Gran, una comunicación municipal accesible; VIRA y Galeón, distintas formas de organizar una experiencia digital. Cada caso explica su alcance para que puedas valorar qué encaja con tu proyecto.',
    process: 'Un proceso compartido',
    steps: [
      ['Entender', 'Empezamos por el contexto, las personas a las que te diriges y las decisiones que debe facilitar el proyecto. Revisamos materiales existentes y acordamos prioridades antes de definir entregables.'],
      ['Dar forma', 'Convertimos esas prioridades en una dirección visual, una estructura de contenidos y aplicaciones concretas. Compartimos avances para revisar el trabajo con criterios acordados.'],
      ['Preparar el siguiente paso', 'Desarrollamos y revisamos los soportes incluidos en el alcance. La entrega debe permitir utilizar la identidad, publicar la web o continuar el producto sin perder coherencia.'],
    ],
    local: 'Girona, Costa Brava y equipos de otros lugares',
    localBody: 'Trabajamos en catalán, castellano e inglés. La proximidad facilita compartir contexto con proyectos de Girona y Costa Brava, y la colaboración en remoto permite mantener un proceso directo con equipos distribuidos. Acordamos la forma de trabajo según las necesidades del proyecto.',
    about: 'Conoce cómo trabajamos', cta: 'Cuéntanos tu proyecto', allProjects: 'Ver todos los proyectos',
    hubTitle: 'Branding, diseño y desarrollo digital',
    hubIntro: 'Trabajamos la marca y el producto digital como partes de un mismo sistema. Desde definir una identidad hasta convertirla en una experiencia web funcional, el punto de partida es entender qué necesita tu negocio y qué espera encontrar la persona que se acerca a él.',
    choose: 'Qué servicio necesita tu proyecto',
    choices: [
      ['Si necesitas definir o renovar tu marca', 'El branding ordena el posicionamiento, la personalidad y el sistema visual. Es el recorrido adecuado cuando la identidad actual ya no representa el proyecto o cuando una nueva iniciativa necesita una base clara. Las aplicaciones se concretan según los puntos de contacto que vayas a utilizar.'],
      ['Si necesitas explicar mejor tu propuesta online', 'El diseño web trabaja la estructura, los contenidos, los recorridos y la interfaz. Ayuda a convertir una oferta compleja en una experiencia comprensible, coherente con la marca y cómoda en móvil. Antes de dibujar pantallas, acordamos qué acciones deben poder realizar las personas.'],
      ['Si tienes un diseño y necesitas publicarlo', 'El desarrollo web convierte la propuesta visual en una implementación real. Definimos las páginas, los componentes, el comportamiento responsive y las integraciones necesarias. También revisamos accesibilidad, rendimiento y la base técnica del SEO antes del lanzamiento.'],
      ['Si la identidad ya existe y necesitas aplicarla', 'El diseño gráfico lleva el lenguaje de marca a piezas concretas: presentaciones, publicaciones, cartelería, comunicación digital o materiales impresos. El objetivo es mantener una expresión reconocible y adaptar la jerarquía y el formato a cada uso.'],
    ],
    disciplines: 'Estrategia, UX/UI, dirección de arte y movimiento',
    disciplinesBody: 'Son disciplinas que conectan los distintos servicios. La estrategia orienta las decisiones; UX/UI organiza la experiencia; la dirección de arte coordina tipografía, composición e imagen; el movimiento ayuda a explicar cambios y relaciones. No todos los proyectos necesitan la misma combinación. La elegimos según su propósito, sus contenidos y las condiciones reales de uso.',
    scope: 'Un alcance claro antes de empezar',
    scopeBody: 'Para preparar una propuesta necesitamos conocer el punto de partida, el público, los materiales disponibles y qué tendría que estar listo al finalizar. A partir de ahí acordamos entregables, responsabilidades y revisiones. Si el proyecto incluye contenidos, varios idiomas, gestión mediante CMS o conexiones con otros sistemas, los definimos expresamente para que el presupuesto responda al trabajo real.',
    established: 'Explora el proceso de cada disciplina',
    privacy: 'Privacidad', legal: 'Aviso legal', studio: 'Estudio',
  },
  ca: {
    headline: 'Dissenyem marques i experiències digitals que la gent recorda',
    intro: 'PALSEC és un estudi de disseny i desenvolupament de la Costa Brava que treballa amb empreses i organitzacions de Girona i d’altres llocs. Connectem estratègia, identitat i tecnologia per donar forma a marques, webs i productes digitals amb criteri.',
    services: 'De la marca a l’experiència digital',
    serviceIntro: 'Una identitat i una web responen a preguntes diferents, però han de parlar el mateix idioma. Podem treballar una part concreta o acompanyar tot el recorregut: definir què necessites comunicar, dissenyar com expressar-ho i construir els suports que ho fan possible.',
    projects: 'Idees que prenen forma',
    proof: 'El portafolis reuneix identitats, sistemes gràfics i interfícies. El Xiringuito mostra una identitat aplicada a restauració; Gent Gran, una comunicació municipal accessible; VIRA i Galeón, diferents maneres d’organitzar una experiència digital. Cada cas explica el seu abast perquè puguis valorar què encaixa amb el teu projecte.',
    process: 'Un procés compartit',
    steps: [
      ['Entendre', 'Comencem pel context, les persones a qui et dirigeixes i les decisions que ha de facilitar el projecte. Revisem els materials existents i acordem prioritats abans de definir els entregables.'],
      ['Donar forma', 'Convertim aquestes prioritats en una direcció visual, una estructura de continguts i aplicacions concretes. Compartim avenços per revisar el treball amb criteris acordats.'],
      ['Preparar el pas següent', 'Desenvolupem i revisem els suports inclosos en l’abast. El lliurament ha de permetre utilitzar la identitat, publicar la web o continuar el producte sense perdre coherència.'],
    ],
    local: 'Girona, Costa Brava i equips d’altres llocs',
    localBody: 'Treballem en català, castellà i anglès. La proximitat facilita compartir context amb projectes de Girona i Costa Brava, i la col·laboració en remot permet mantenir un procés directe amb equips distribuïts. Acordem la manera de treballar segons les necessitats del projecte.',
    about: 'Coneix com treballem', cta: 'Explica’ns el teu projecte', allProjects: 'Veure tots els projectes',
    hubTitle: 'Branding, disseny i desenvolupament digital',
    hubIntro: 'Treballem la marca i el producte digital com a parts d’un mateix sistema. Des de definir una identitat fins a convertir-la en una experiència web funcional, el punt de partida és entendre què necessita el teu negoci i què espera trobar la persona que s’hi acosta.',
    choose: 'Quin servei necessita el teu projecte',
    choices: [
      ['Si necessites definir o renovar la marca', 'El branding ordena el posicionament, la personalitat i el sistema visual. És el recorregut adequat quan la identitat actual ja no representa el projecte o quan una iniciativa nova necessita una base clara. Les aplicacions es concreten segons els punts de contacte que hagis d’utilitzar.'],
      ['Si necessites explicar millor la proposta en línia', 'El disseny web treballa l’estructura, els continguts, els recorreguts i la interfície. Ajuda a convertir una oferta complexa en una experiència entenedora, coherent amb la marca i còmoda en mòbil. Abans de dibuixar pantalles, acordem quines accions han de poder fer les persones.'],
      ['Si tens un disseny i necessites publicar-lo', 'El desenvolupament web converteix la proposta visual en una implementació real. Definim les pàgines, els components, el comportament responsive i les integracions necessàries. També revisem accessibilitat, rendiment i la base tècnica del SEO abans del llançament.'],
      ['Si la identitat ja existeix i necessites aplicar-la', 'El disseny gràfic porta el llenguatge de marca a peces concretes: presentacions, publicacions, cartelleria, comunicació digital o materials impresos. L’objectiu és mantenir una expressió recognoscible i adaptar la jerarquia i el format a cada ús.'],
    ],
    disciplines: 'Estratègia, UX/UI, direcció d’art i moviment',
    disciplinesBody: 'Són disciplines que connecten els diferents serveis. L’estratègia orienta les decisions; UX/UI organitza l’experiència; la direcció d’art coordina tipografia, composició i imatge; el moviment ajuda a explicar canvis i relacions. No tots els projectes necessiten la mateixa combinació. La triem segons el propòsit, els continguts i les condicions reals d’ús.',
    scope: 'Un abast clar abans de començar',
    scopeBody: 'Per preparar una proposta necessitem conèixer el punt de partida, el públic, els materials disponibles i què hauria d’estar llest en acabar. A partir d’aquí acordem entregables, responsabilitats i revisions. Si el projecte inclou continguts, diversos idiomes, gestió amb CMS o connexions amb altres sistemes, els definim expressament perquè el pressupost respongui al treball real.',
    established: 'Explora el procés de cada disciplina',
    privacy: 'Privacitat', legal: 'Avís legal', studio: 'Estudi',
  },
  en: {
    headline: 'We design brands and digital experiences people remember',
    intro: 'PALSEC is a design and development studio on the Costa Brava, working with businesses and organisations in Girona and beyond. We connect strategy, identity and technology to shape considered brands, websites and digital products.',
    services: 'From brand to digital experience',
    serviceIntro: 'An identity and a website answer different questions, but they need to speak the same language. We can focus on a specific part or support the whole journey: defining what you need to communicate, designing how to express it and building the applications that make it possible.',
    projects: 'Ideas taking shape',
    proof: 'Our portfolio brings together identities, graphic systems and interfaces. El Xiringuito explores a restaurant identity; Gent Gran, accessible municipal communication; VIRA and Galeón, different ways of organising a digital experience. Each case explains its scope so you can assess what relates to your project.',
    process: 'A shared process',
    steps: [
      ['Understand', 'We begin with the context, the people you want to reach and the decisions the project needs to support. We review existing materials and agree priorities before defining deliverables.'],
      ['Shape', 'We turn those priorities into a visual direction, content structure and specific applications. We share work in progress so that feedback follows the criteria we have agreed.'],
      ['Prepare the next step', 'We develop and review the applications included in the scope. The handover should let you use the identity, publish the website or continue the product without losing coherence.'],
    ],
    local: 'Girona, Costa Brava and teams further afield',
    localBody: 'We work in Catalan, Spanish and English. Being nearby helps us share context with projects in Girona and Costa Brava, while remote collaboration keeps the process direct for distributed teams. We agree how to work together around the needs of each project.',
    about: 'Get to know our approach', cta: 'Tell us about your project', allProjects: 'View all projects',
    hubTitle: 'Branding, design and digital development',
    hubIntro: 'We treat the brand and the digital product as parts of the same system. From defining an identity to turning it into a functioning web experience, we start by understanding what your business needs and what people expect to find when they encounter it.',
    choose: 'Which service does your project need?',
    choices: [
      ['When you need to define or renew your brand', 'Branding brings structure to positioning, personality and the visual system. It is the right starting point when your current identity no longer represents the project, or when a new initiative needs a clear foundation. Specific applications depend on the touchpoints you will actually use.'],
      ['When you need to explain your offer better online', 'Web design addresses structure, content, journeys and the interface. It helps turn a complex offer into an understandable experience that feels consistent with the brand and comfortable on mobile. Before designing screens, we agree which actions people need to be able to take.'],
      ['When you have a design and need to publish it', 'Web development turns a visual proposal into a working implementation. We define pages, components, responsive behaviour and the integrations you need. Accessibility, performance and the technical foundations of SEO are also reviewed before launch.'],
      ['When the identity exists and needs to be applied', 'Graphic design carries the brand language into specific materials: presentations, publications, posters, digital communication or print. The aim is to maintain a recognisable expression while adapting hierarchy and format to each use.'],
    ],
    disciplines: 'Strategy, UX/UI, art direction and motion',
    disciplinesBody: 'These disciplines connect our services. Strategy guides decisions; UX/UI organises the experience; art direction coordinates typography, composition and imagery; motion helps explain changes and relationships. Every project needs a different combination. We choose it around the purpose, the content and the actual conditions in which people will use the work.',
    scope: 'A clear scope before work begins',
    scopeBody: 'To prepare a proposal, we need to understand the starting point, the audience, available materials and what should be ready at the end. We then agree deliverables, responsibilities and review stages. Content, multiple languages, CMS editing and connections to other systems are defined explicitly where needed, so the estimate reflects the real work involved.',
    established: 'Explore the process behind each discipline',
    privacy: 'Privacy', legal: 'Legal notice', studio: 'Studio',
  },
} satisfies Record<Lang, unknown>
